### ISSUE TITLE
IB QM notes don't appear on the website

### ISSUE THREAD

**Issue by juliangilbey** [zeramorphic/cambridge-maths-notes#15]
Hi!  Amazing lecture notes, thank you!
For some reason, the link https://thirdsgames.co.uk/gh/maths-compiled/ib/qm/build/main.pdf does not work - it gives a 500 Internal Server Error.  Perhaps there is a LaTeX error that has prevented it from compiling?

**Comment by zeramorphic** [comment]
Thanks for pointing out the error! I just wrote the link wrong - it's `quantum` not `qm`. I've fixed the website now, and the notes should be immediately visible.
